### ISSUE TITLE
Error on installing dependencies

### ISSUE THREAD

**Issue by AlidotSal** [geckosio/simple-chat-app-example#3]
After cloning the project when I try to install npm packages, It gives error about node-datachannel package.

**Comment by yandeu** [comment]
Make sure your dev environment is [node-datachannel](https://github.com/murat-dogan/node-datachannel#readme) compatible.
It does not support Node.js V17 yet.

**Comment by AlidotSal** [comment]
Thanks. It works with Node version 16.13.0
